-- Residents: standalone master registry of individuals, profiled independently
-- of household assignment so the same record can be reused across different
-- profiling programs (households being just one of them).
-- Depends on address_barangay (base address schema) and users (002_roles_users_assignments.sql).

CREATE TABLE IF NOT EXISTS `residents` (
  `id` int NOT NULL AUTO_INCREMENT,
  `barangay_id` int NOT NULL,
  `resident_no` varchar(30) NOT NULL,
  `last_name` varchar(100) NOT NULL,
  `first_name` varchar(100) NOT NULL,
  `middle_name` varchar(100) DEFAULT NULL,
  `suffix` varchar(20) DEFAULT NULL,
  `sex` enum('Male','Female') NOT NULL,
  `birthdate` date NOT NULL,
  `birthplace` varchar(150) DEFAULT NULL,
  `civil_status` varchar(30) NOT NULL,
  `religion` varchar(50) DEFAULT NULL,
  `citizenship` varchar(50) NOT NULL DEFAULT 'Filipino',
  `blood_type` varchar(5) DEFAULT NULL,
  `purok_sitio` varchar(100) DEFAULT NULL,
  `address_line` varchar(150) DEFAULT NULL,
  `contact_number` varchar(20) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `occupation` varchar(150) DEFAULT NULL,
  `employer` varchar(150) DEFAULT NULL,
  `monthly_income` decimal(10,2) DEFAULT NULL,
  `educational_attainment` varchar(50) DEFAULT NULL,
  `national_id_no` varchar(50) DEFAULT NULL,
  `voters_id_no` varchar(50) DEFAULT NULL,
  `sss_no` varchar(50) DEFAULT NULL,
  `gsis_no` varchar(50) DEFAULT NULL,
  `pagibig_no` varchar(50) DEFAULT NULL,
  `philhealth_no` varchar(50) DEFAULT NULL,
  `tin_no` varchar(50) DEFAULT NULL,
  `is_pwd` tinyint(1) NOT NULL DEFAULT '0',
  `is_senior_citizen` tinyint(1) NOT NULL DEFAULT '0',
  `is_solo_parent` tinyint(1) NOT NULL DEFAULT '0',
  `is_4ps_beneficiary` tinyint(1) NOT NULL DEFAULT '0',
  `is_ofw` tinyint(1) NOT NULL DEFAULT '0',
  `is_indigenous` tinyint(1) NOT NULL DEFAULT '0',
  `indigenous_group` varchar(100) DEFAULT NULL,
  `remarks` tinytext,
  `archive` tinyint(1) NOT NULL DEFAULT '0',
  `created_by` int DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `residents_barangay_resident_no_unique` (`barangay_id`, `resident_no`),
  KEY `residents_barangay_id_foreign` (`barangay_id`),
  KEY `residents_created_by_foreign` (`created_by`),
  CONSTRAINT `residents_barangay_id_foreign` FOREIGN KEY (`barangay_id`) REFERENCES `address_barangay` (`id`),
  CONSTRAINT `residents_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
